# PART : 5 - VECTORISERS & COSINE SIMILARITY 

# TASK 1: Import CountVectorizer

In [100]:
#VECTORISERS TO CONVERT WORDS INTO NUMBERS
from sklearn.feature_extraction.text import CountVectorizer
#from sklearn.feature_extraction.text import TfidVectorizer

# Task 2: Define Corpus

In [101]:
vect = CountVectorizer(binary = True)
corpus = ["Tessaract is good character recognition engine", "optical character recognition is significant"]
vect.fit(corpus) # It will do some indexing to uniqe words in given text

CountVectorizer(analyzer='word', binary=True, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

# Task 3: Create Vocabulary

In [102]:
#function to create vocabulary of words
vocab = vect.vocabulary_ 

In [103]:
#sort the vocabulary
for key in sorted(vocab.keys()):
    print("{}:{}".format(key, vocab[key]))

character:0
engine:1
good:2
is:3
optical:4
recognition:5
significant:6
tessaract:7


# Task 4: Transform into Vector

In [104]:
#transform into vector, from words to binary number in array format
print(vect.transform(["This is good optical illusion"]).toarray())

[[0 0 1 1 1 0 0 0]]


In [105]:
print(vect.transform(corpus).toarray())

[[1 1 1 1 0 1 0 1]
 [1 0 0 1 1 1 1 0]]


# Task 5: Cosine Similarity

In [106]:
from sklearn.metrics.pairwise import cosine_similarity

In [107]:
similarity = cosine_similarity(vect.transform(["Google Cloud Vision is a character recognition engine"]).toarray(), vect.transform(["OCR is an optical character recognition engine"]).toarray())

In [108]:
print(similarity)

[[0.894427]]


# Practice Example

In [109]:
# Task 3: Vectorisers & cosine similarity
from sklearn.feature_extraction.text import CountVectorizer

In [110]:
vect = CountVectorizer(binary = True)
corpus = ["silver is good conductor of electricity", "wood is not conductor"]
vect.fit(corpus) # It will do some indexing to uniqe words in given text

CountVectorizer(analyzer='word', binary=True, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [111]:
vocab = vect.vocabulary_ #Inbuit function to create vocabulary of unique wrods

In [112]:
for key in sorted(vocab.keys()):
    print("{}:{}".format(key, vocab[key]))

conductor:0
electricity:1
good:2
is:3
not:4
of:5
silver:6
wood:7


In [113]:
#transform into vector, from words to binary number in array format
print(vect.transform(["This is good optical illusion"]).toarray())

[[0 0 1 1 0 0 0 0]]


In [114]:
print(vect.transform(corpus).toarray())

[[1 1 1 1 0 1 1 0]
 [1 0 0 1 1 0 0 1]]


In [115]:
from sklearn.metrics.pairwise import cosine_similarity

In [116]:
similarity = cosine_similarity(vect.transform(["gold is conductor"]).toarray(), vect.transform(["wood is not conductor"]).toarray())

In [117]:
print(similarity)

[[0.707107]]
